site:
  - type: Record
    name: user
    label: User
records:
  user:
    list:
      fields:
        - type: _id
        - name: username
          type: String
        - name: email
          type: String
        - type: _created_at
        - type: _updated_at
      filters:
        - name: username
          type: String
          label: Username
        - name: email
          type: String
          label: Email
        - name: _created_at
          type: DateTime
          label: Created at
    show:
      fields:
        - type: _id
        - name: username
          type: String
        - name: email
          type: String
        - type: _created_at
        - type: _updated_at
    edit:
      fields:
        - type: _id
        - name: username
          type: String
        - name: email
          type: String
        - type: _created_at
        - type: _updated_at
    new:
      fields:
        - type: _id
        - name: username
          type: String
        - name: email
          type: String

