imports:
  import-product:
    record_type: product
    fields: &product_csv_fields
      - name: _id
      - name: name
      - name: description
      - name: picture


exports:
  export-product:
    record_type: product
    fields: *product_csv_fields


site:
  - type: user_management
    label: USER
  - type: push_notifications
    label: PUSH
  - type: file_import
    label: FILE
  - type: space
  - type: record
    name: user
  - type: record
    name: payment
  - type: record
    name: order
  - type: record
    name: shipping_order
  - type: record
    name: product

records:
  user:
    list:
      item_actions:
        - type: show_button
        - type: edit_button
        - type: link
          label: View Orders
          href: /records/order?filter=%5B%7B"name"%3A"customer"%2C"query"%3A"Contains"%2C"value"%3A%5B"{record.contact_name}"%5D%7D%5D
      filters:
        - type: general
          label: Customer data
          name:
            - _id
            - contact_name
            - email
            - phone
      fields:
        - &user_field_contact_name
          name: contact_name
          type: string
        - &user_field_phone
          name: phone
          type: string
        - &user_field_email
          name: email
          type: string
    show:
      fields: &user_detail_fields
        - name: _id
        - name: _created_at
        - *user_field_contact_name
        - &user_field_username
          name: username
          type: string
        - *user_field_phone
        - *user_field_email
        - &user_field_profile_picture
          name: profile_picture
          type: image
        - &user_field_address
          name: address
          type: text_area
        - &user_field_payment_methods
          name: payment_methods
          type: embedded_reference_list
          reference_via_back_reference: payment_method
          reference_from_field: customer
          reference_position_field: payment_priority
          reference_reorder_enabled: true
          reference_fields:
            - name: type
              type: dropdown
              null:
                enabled: false
                label: Unknown
              custom:
                enabled: false
                label: Unknown
              options:
                - label: Credit Card
                  value: credit_card
                - label: Paypal
                  value: paypal
            - name: account_id
              type: string
            - name: active
              type: boolean
    edit:
      fields: *user_detail_fields
    new:
      fields: *user_detail_fields


  payment:
    list:
      filters:
        - name: payment_method
          type: reference
          reference_target: payment_method
          reference_field_name: type
          nullable: false
      fields:
        - name: _created_at
        - &payment_field_user_contact_name
          name: customer
          type: reference
          reference_target: user
          reference_field_name: contact_name
        - &payment_field_user_payment_method
          name: payment_method
          type: reference
          reference_target: payment_method
          reference_field_name: type
        - &payment_field_amount
          name: amount
          type: number
    show:
      fields:
        - name: _created_at
        - *payment_field_user_contact_name
        - *payment_field_amount
        - *payment_field_user_payment_method

  payment_method: {}

  order:
    list:
      filters: &order_list_filters
        - name: customer
          type: reference
          reference_target: user
          reference_field_name: contact_name
          nullable: false
      fields: &order_fields
        - &order_field_order_number
          name: _id
          label: Order Number
        - &order_field_user_contact_name
          name: customer
          type: reference
          reference_target: user
          reference_field_name: contact_name
        - &order_field_order_date
          name: _created_at
          label: Order Date
        - &order_field_due_date
          name: due_date
          label: Due date
          type: date_time
        - &order_field_status
          name: status
          type: dropdown
          null:
            enabled: false
            label: Unknown
          custom:
            enabled: true
          options:
            - label: Pending
              value: pending
            - label: Shipping
              value: shipping
            - label: Shipped
              value: shipped
    show: &order_show_page
      fields:
        - *order_field_order_number
        - *order_field_user_contact_name
        - *order_field_order_date
        - *order_field_due_date
        - *order_field_status
        - &order_field_comment
          name: comment
          type: text_area
        - &order_field_products
          name: products
          type: reference_list
          reference_via_association_record: order_product
          reference_target: product
          reference_field_name: name
    edit: &order_edit_page
      fields:
        - *order_field_order_number
        - <<: *order_field_user_contact_name
          editable: false
        - *order_field_order_date
        - *order_field_due_date
        - *order_field_status
        - *order_field_comment
        - <<: *order_field_products
          editable: false

  shipping_order:
    record_type: order
    list:
      predicates:
        - name: status
          predicate: equal_to
          value: shipping
      filters: *order_list_filters
      fields: *order_fields
    show: *order_show_page
    edit: *order_edit_page

  product:
    list:
      actions:
        - type: import
          name: import-product
          label: Import
        - type: export
          name: export-product
          label: Export
      filters:
        - name: name
          type: string
        - name: active
          type: boolean
      fields:
        - &product_field_name
          name: name
          type: string
        - &product_field_active
          name: active
          type: boolean
    show:
      fields:
        - name: _id
        - *product_field_name
        - &product_field_description
          name: description
          type: text_area
        - &product_field_picture
          name: picture
          type: image
        - *product_field_active
    edit:
      fields:
        - name: _id
        - *product_field_description
        - <<: *product_field_name
          editable: false
        - *product_field_picture
        - *product_field_active


association_records:
  order_product:
    fields:
      - name: order
        type: reference
        reference_target: order
      - name: product
        type: reference
        reference_target: product
