imports:
  import-product:
    record_type: product
    fields: &product_csv_fields
      - name: _id
      - name: name
      - name: description
      - name: picture


exports:
  export-product:
    record_type: product
    fields: *product_csv_fields


site:
  - type: UserManagement
    label: USER
  - type: PushNotifications
    label: PUSH
  - type: FileImport
    label: FILE
  - type: Space
  - type: Record
    name: user
  - type: Record
    name: payment
  - type: Record
    name: order
  - type: Record
    name: shipping_order
  - type: Record
    name: product

records:
  user:
    list:
      item_actions:
        - type: ShowButton
        - type: EditButton
        - type: Link
          label: View Orders
          href: /records/order?filter=%5B%7B"name"%3A"customer"%2C"query"%3A"Contains"%2C"value"%3A%5B"{record.contact_name}"%5D%7D%5D
      filters:
        - type: General
          label: Customer data
          name:
            - _id
            - contact_name
            - email
            - phone
      fields:
        - &user_field_contact_name
          name: contact_name
          type: String
        - &user_field_phone
          name: phone
          type: String
        - &user_field_email
          name: email
          type: String
    show:
      fields: &user_detail_fields
        - name: _id
        - name: _created_at
        - *user_field_contact_name
        - &user_field_username
          name: username
          type: String
        - *user_field_phone
        - *user_field_email
        - &user_field_profile_picture
          name: profile_picture
          type: Image
        - &user_field_address
          name: address
          type: TextArea
        - &user_field_payment_methods
          name: payment_methods
          type: EmbeddedReferenceList
          reference_via_back_reference: payment_method
          reference_from_field: user
          reference_position_field: payment_priority
          reference_reorder_enabled: true
          reference_fields:
            - name: type
              type: Dropdown
              null:
                enabled: false
                label: Unknown
              custom:
                enabled: false
                label: Unknown
              options:
                - label: Credit Card
                  value: credit_card
                - label: Paypal
                  value: paypal
            - name: account_id
              type: String
            - name: active
              type: Boolean
    edit:
      fields: *user_detail_fields
    new:
      fields: *user_detail_fields


  payment:
    list:
      filters:
        - name: payment_method
          type: Reference
          reference_target: payment_method
          reference_field_name: type
          nullable: false
      fields:
        - name: _created_at
        - &payment_field_user_contact_name
          name: customer
          type: Reference
          reference_target: user
          reference_field_name: contact_name
        - &payment_field_user_payment_method
          name: payment_method
          type: Reference
          reference_target: payment_method
          reference_field_name: type
        - &payment_field_amount
          name: amount
          type: Number
    show:
      fields:
        - name: _created_at
        - *payment_field_user_contact_name
        - *payment_field_amount
        - *payment_field_user_payment_method

  payment_method: {}

  order:
    list:
      filters: &order_list_filters
        - name: customer
          type: Reference
          reference_target: user
          reference_field_name: contact_name
          nullable: false
      fields: &order_fields
        - &order_field_order_number
          name: _id
          label: Order Number
        - &order_field_user_contact_name
          name: customer
          type: Reference
          reference_target: user
          reference_field_name: contact_name
        - &order_field_order_date
          name: _created_at
          label: Order Date
        - &order_field_due_date
          name: due_date
          label: Due date
          type: DateTime
        - &order_field_status
          name: status
          type: Dropdown
          null:
            enabled: false
            label: Unknown
          custom:
            enabled: true
          options:
            - label: Pending
              value: pending
            - label: Shipping
              value: shipping
            - label: Shipped
              value: shipped
    show: &order_show_page
      fields:
        - *order_field_order_number
        - *order_field_user_contact_name
        - *order_field_order_date
        - *order_field_due_date
        - *order_field_status
        - &order_field_comment
          name: comment
          type: TextArea
        - &order_field_products
          name: products
          type: ReferenceList
          reference_via_association_record: order_product
          reference_target: product
          reference_field_name: name
    edit: &order_edit_page
      fields:
        - *order_field_order_number
        - <<: *order_field_user_contact_name
          editable: false
        - *order_field_order_date
        - *order_field_due_date
        - *order_field_status
        - *order_field_comment
        - <<: *order_field_products
          editable: false

  shipping_order:
    record_type: order
    list:
      predicates:
        - name: status
          predicate: EqualTo
          value: shipping
      filters: *order_list_filters
      fields: *order_fields
    show: *order_show_page
    edit: *order_edit_page

  product:
    list:
      actions:
        - type: Import
          name: import-product
          label: Import
        - type: Export
          name: export-product
          label: Export
      filters:
        - name: name
          type: String
        - name: active
          type: Boolean
      fields:
        - &product_field_name
          name: name
          type: String
        - &product_field_active
          name: active
          type: Boolean
    show:
      fields:
        - name: _id
        - *product_field_name
        - &product_field_description
          name: description
          type: TextArea
        - &product_field_picture
          name: picture
          type: Image
        - *product_field_active
    edit:
      fields:
        - name: _id
        - *product_field_description
        - <<: *product_field_name
          editable: false
        - *product_field_picture
        - *product_field_active


association_records:
  order_product:
    fields:
      - name: order
        type: Reference
        reference_target: order
      - name: product
        type: Reference
        reference_target: product
