default_settings:
  timezone: Asia/Hong_Kong

user_management:
  verification:
    editable: false
    fields:
      - name: email
        editable: true
      - name: phone
        label: Phone number
        editable: true

imports:
  import-field-demo:
    record_type: field_demo
    identifier: name
    handle_duplicated_identifier: throw_error
    fields:
      - name: name
        label: Name
      - name: textarea
      - name: dropdown
      - name: wysiwyg
      - name: datetime
      - name: boolean
      - name: integer
      - name: number
      - name: reference
        reference_target: ref_demo
        reference_field_name: name
        handle_duplicated_reference: use_first
  import-asset-demo:
    record_type: field_demo
    identifier: name
    fields:
      - name: name
        label: Name
      - name: imageasset

exports:
  export-field-demo:
    record_type: field_demo
    fields:
      - name: _id
      - name: _created_at
      - name: _updated_at
      - name: name
        label: Name
      - name: textarea
      - name: dropdown
      - name: wysiwyg
      - name: datetime
      - name: boolean
      - name: integer
      - name: number
      - name: reference
        reference_target: ref_demo
        reference_field_name: name
      - name: back_refs
        reference_via_back_reference: back_ref_demo
        reference_from_field: reference
        reference_fields:
          - name: _id
            label: Back ref {index} - ID
          - name: name
            label: Back ref {index} - Name

push_notifications:
  enabled: true
  filters:
    - name: name
      type: string
      label: Name

site:
  - type: user_management
    label: USER
  - type: push_notifications
    label: PUSH
  - type: file_import
    label: FILE
  - type: space
  - type: record
    name: field_demo
  - type: record
    name: field_demo_deleted
  - type: space
    size: large

records:
  field_demo:
    list:
      predicates:
        - name: deleted
          predicate: not_equal_to
          value: true
      default_sort:
        name: name
        ascending: false
      actions:
        - type: add_button
        - type: import
          name: import-field-demo
          label: Import records
        - type: import
          name: import-field-demo
          label: Import (Atomic)
          atomic: true
        - type: import
          name: import-asset-demo
          label: Import with asset
        - type: export
          name: export-field-demo
          label: Export records
      item_actions:
        - type: show_button
        - type: edit_button
        - type: link
          label: Search
          href: https://www.google.com/search?q={record.name}
          target: _blank
      fields:
        - name: _id
        - name: _created_at
        - name: _updated_at
        - name: name
          label: Name
          type: string
        - name: textarea
          type: text_area
        - name: dropdown
          type: string
        - name: wysiwyg
          type: wysiwyg
        - name: datetime
          type: date_time
        - name: boolean
          type: boolean
        - name: integer
          type: integer
        - name: number
          type: number
        - name: reference
          type: reference
          reference_target: ref_demo
          reference_field_name: name
        - name: back_refs
          type: reference_list
          reference_via_back_reference: back_ref_demo
          reference_from_field: reference
          reference_field_name: name
        - name: imageasset
          type: image
        - name: fileasset
          type: asset
      filters:
        - name: _id
          label: ID
          type: string
        - name: _created_at
          label: CreatedAt
          type: date_time
        - name: _updated_at
          label: UpdatedAt
          type: date_time
        - name: name
          label: Name
          type: string
        - name: datetime
          type: date_time
        - name: boolean
          type: boolean
        - name: integer
          type: integer
        - name: reference
          type: reference
          reference_target: ref_demo
          reference_field_name: name
          nullable: true
    show:
      fields:
        - name: _id
        - name: _created_at
        - name: _updated_at
        - name: name
          label: Name
          type: string
        - name: textarea
          type: text_area
        - name: dropdown
          type: string
        - name: wysiwyg
          type: wysiwyg
        - name: datetime
          type: date_time
          timezone: America/New_York
        - name: boolean
          type: boolean
        - name: integer
          type: integer
        - name: number
          type: number
        - name: reference
          type: reference
          reference_target: ref_demo
          reference_field_name: name
        - name: back_refs
          type: reference_list
          reference_via_back_reference: back_ref_demo
          reference_from_field: reference
          reference_field_name: name
        - name: asso_refs
          type: reference_list
          reference_via_association_record: field_asso_ref
          reference_target: asso_ref_demo
          reference_field_name: name
        - name: back_refs_embedded
          type: embedded_reference_list
          reference_via_back_reference: back_ref_demo
          reference_from_field: reference
          reference_position_field: field_demo_position
          reference_position_ascending: false
          reference_fields:
            - name: _id
            - name: name
              type: string
        - name: asso_refs_embedded
          type: embedded_reference_list
          reference_via_association_record: field_asso_ref
          reference_target: asso_ref_demo
          reference_fields:
            - name: _id
            - name: name
              type: string
        - name: imageasset
          type: image
        - name: fileasset
          type: asset
        - name: deleted
          type: boolean
    edit:
      fields:
        - name: _id
        - name: _created_at
        - name: _updated_at
        - name: name
          label: Name
          type: string
          validations:
            - when: substring(value, 0, 1) != "_"
              expression: length(value) < 10
              message: Too long.
            - expression: lower(value) not in ("admin", "god")
              message: Reserved name.
        - name: textarea
          type: text_area
        - name: dropdown
          type: dropdown
          null:
            enabled: false
            label: Undefined
          custom:
            enabled: true
          options:
            - label: Option A
              value: A
            - label: Option B
              value: B
            - label: Option S
              value: S
        - name: wysiwyg
          type: wysiwyg
        - name: datetime
          type: date_time
        - name: boolean
          type: boolean
        - name: integer
          type: integer
        - name: number
          type: number
        - name: reference
          type: reference
          reference_target: ref_demo
          reference_field_name: name
        - name: back_refs
          type: reference_list
          reference_via_back_reference: back_ref_demo
          reference_from_field: reference
          reference_field_name: name
        - name: back_refs_embedded
          type: embedded_reference_list
          reference_via_back_reference: back_ref_demo
          reference_from_field: reference
          reference_position_field: field_demo_position
          reference_position_ascending: true
          reference_fields:
            - name: _id
            - name: name
              type: string
        - name: asso_refs_embedded
          type: embedded_reference_list
          reference_via_association_record: field_asso_ref
          reference_target: asso_ref_demo
          reference_reorder_enabled: false
          reference_fields:
            - name: _id
            - name: name
              type: string
        - name: imageasset
          type: image
        - name: fileasset
          type: asset
          validations:
            - required: true
            - expression: regex(get(value, "content_type"), "^(image|video)")
        - name: deleted
          type: boolean
          default_value: false
    new:
      fields:
        - name: _id
        - name: _created_at
        - name: _updated_at
        - name: name
          label: Name
          type: string
        - name: textarea
          type: text_area
        - name: dropdown
          type: dropdown
          null:
            enabled: false
            label: Undefined
          custom:
            enabled: true
          options:
            - label: Option A
              value: A
            - label: Option B
              value: B
            - label: Option S
              value: S
        - name: wysiwyg
          type: wysiwyg
        - name: datetime
          type: date_time
        - name: boolean
          type: boolean
        - name: integer
          type: integer
        - name: number
          type: number
        - name: reference
          type: reference
          reference_target: ref_demo
          reference_field_name: name
        - name: back_refs
          type: reference_list
          reference_via_back_reference: back_ref_demo
          reference_from_field: reference
          reference_field_name: name
        - name: back_refs_embedded
          type: embedded_reference_list
          reference_via_back_reference: back_ref_demo
          reference_from_field: reference
          reference_position_field: field_demo_position
          reference_position_ascending: true
          reference_fields:
            - name: _id
            - name: name
              type: string
        - name: asso_refs_embedded
          type: embedded_reference_list
          reference_via_association_record: field_asso_ref
          reference_target: asso_ref_demo
          reference_reorder_enabled: false
          reference_fields:
            - name: _id
            - name: name
              type: string
        - name: imageasset
          type: image
        - name: fileasset
          type: asset
        - name: deleted
          type: boolean
          default_value: false
  field_demo_deleted:
    record_type: field_demo
    list:
      predicates:
        - name: deleted
          predicate: equal_to
          value: true
      fields:
        - name: _id
        - name: _created_at
        - name: _updated_at
        - name: name
          label: Name
          type: string
    show:
      fields:
        - name: _id
        - name: _created_at
        - name: _updated_at
        - name: name
          label: Name
          type: string
  ref_demo:
    show:
      fields:
        - name: _id
        - name: name
          label: Name
          type: string
        - name: field_references
          type: reference_list
          reference_via_back_reference: field_demo
          reference_from_field: reference
          reference_field_name: name
    edit:
      fields:
        - name: _id
        - name: name
          label: Name
          type: string
        - name: field_demos
          type: reference_list
          reference_via_back_reference: field_demo
          reference_from_field: reference
          reference_field_name: name
    new:
      fields:
        - name: _id
        - name: name
          label: Name
          type: string
        - name: field_demos
          type: reference_list
          reference_via_back_reference: field_demo
          reference_from_field: reference
          reference_field_name: name
  back_ref_demo:
    show:
      fields:
        - name: _id
        - name: reference
          type: reference
          reference_target: field_demo
          reference_field_name: name
        - name: name
          label: Name
          type: string
    edit:
      fields:
        - name: _id
        - name: reference
          type: reference
          reference_target: field_demo
          reference_field_name: name
        - name: name
          label: Name
          type: string
    new:
      fields:
        - name: _id
        - name: reference
          type: reference
          reference_target: field_demo
          reference_field_name: name
        - name: name
          label: Name
          type: string
  asso_ref_demo:
    show:
      fields:
        - name: _id
        - name: name
          label: Name
          type: string

association_records:
  field_asso_ref:
    fields:
      - name: field_demo
        type: reference
        reference_target: field_demo
      - name: asso_ref_demo
        type: reference
        reference_target: asso_ref_demo
