env:
  browser: true
  jest: true
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
plugins:
  - jsx-a11y
rules:
  indent:
    - error
    - 2
  jsx-a11y/label-has-for:
    - 2
    - components:
      - Label
      required:
        some:
          - nesting
          - id
  linebreak-style:
    - error
    - unix
  no-console: 0
  no-debugger: 0
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - always
