dist: trusty
sudo: false

stages:
  - test
  - name: deploy
    if: type != pull_request

jobs:
  include:
    # test
    - stage: test
      language: node_js
      node_js: "8"
      cache: &node_cache
        directories:
          - client/node_modules
      install: &node_install
        - npm --prefix=client ci
      script:
        - cd client
        - node_modules/.bin/prettier --list-different "src/**/*.ts*"
        - npm run lint
        - CI=1 npm run test
        - npm run build

    - stage: test
      language: python
      python: 3.5
      install:
        - pip install -r test_requirements.txt
      script:
        - isort -c -rc -sl skygear_content_manager
        - yapf -d -r skygear_content_manager
        - pylama skygear_content_manager

    # deploy
    - &deploy_client
      stage: deploy
      if: branch = master
      language: node_js
      node_js: "8"
      cache: *node_cache
      install: *node_install
      script:
        - npm --prefix=client run build
      deploy:
        - &deploy_client_to_s3
          provider: s3
          bucket: "code.skygear.io"
          skip_cleanup: true
          local_dir: client/build
          on:
            branch: master
          upload_dir: js/content-manager/$(git describe --always --tags)

    - <<: *deploy_client
      if: tag IS present
      deploy:
        - <<: *deploy_client_to_s3
          on:
            tags: true
          upload_dir: js/content-manager/${TRAVIS_TAG}

    - stage: deploy
      if: branch = master
      language: node_js
      node_js: "8"
      install: echo skip install
      script: echo skip script
      deploy:
        - provider: script
          script: ./scripts/deploy.sh

notifications:
  slack:
    secure: kFX9V98DQtvacmrFLoZNzjUhdccFiXHX8emP4sQRG1xEj35sA3J+xiKCQM7cEiOFJQ90k5uXWVHD/33DmMobWbJ7waXY+dcDSTaiGtqm8X2c1S9oXili7WMlO088PSmpI1wcVmvqoJhbmUzhnBN1NfA6mvRcSwIbXu+yAuMfolUGtOfIU4WYCyuBh9rO5AS5zN5dguxDYCT7pxNJVAp8MOEHsrZ09pYzkwFnhDopgEYQMntoRKSPcx7S1/h8eNXF06Jn7PyO4jhUHuGWFPHqB5J0VwlCxhJxYHUMcRy82YlDNWwsFMPceo0TF0vGuiksWog5qKRwMLOPbDNHLDq5Gj9w2QeK54seEJP0+n3lV8sqUKsgfETjCcK/f1JgVhiiiXi4GlSMc9JpW8c8wTA0hGRgku5te8VK7y6laCfJ5H7Au72fW6eAi7LGz914oGFlJVjLy9CrDPT+0not4b9AAUOYrt/BvN7FsuqymTgQFJsiS0gQ8bvvQagh0qw7PU5/GGrvmYoCvqHk9OD+zq+HSOkwka8DSMyvDdpJgdR3DSPfsgQYnmLi105p/9jCnYXqEXhTp769YyxHKaImSPXBLfZA89etL1/8XX5wlpKdkBdgYo/6MKPy8/Xcq2znBk79N1O7XQb62JlGtZZRdAghZOOuSVdoaxc7AxooNTN/6rU=
