import * as fs from 'fs';
import * as yaml from 'js-yaml';
import * as process from 'process';
import { parseCmsConfig } from '..';

// tslint:disable:object-literal-sort-keys
test('parseCmsConfig should parse example config', () => {
  const text = fs.readFileSync(process.cwd() + '/example/cms-config.yaml', {
    encoding: 'utf-8',
  });
  const parsed = yaml.safeLoad(text);
  const config = parseCmsConfig(parsed);
  expect(config).toEqual({
    associationRecordByName: {
      field_asso_ref: {
        cmsRecord: { name: 'field_asso_ref', recordType: 'field_asso_ref' },
        referenceConfigPair: [
          {
            compact: false,
            name: 'field_demo',
            label: 'Field demo',
            displayFieldName: '_id',
            targetCmsRecord: { name: 'field_demo', recordType: 'field_demo' },
            type: 'Reference',
          },
          {
            compact: false,
            name: 'asso_ref_demo',
            label: 'Asso ref demo',
            displayFieldName: '_id',
            targetCmsRecord: {
              name: 'asso_ref_demo',
              recordType: 'asso_ref_demo',
            },
            type: 'Reference',
          },
        ],
      },
    },
    fileImport: {
      enabled: true,
    },
    pushNotifications: {
      enabled: true,
      filterUserConfigs: [
        { name: 'name', label: 'Name', nullable: false, type: 'String' },
      ],
    },
    records: {
      field_demo: {
        cmsRecord: { name: 'field_demo', recordType: 'field_demo' },
        edit: {
          actions: [],
          cmsRecord: { name: 'field_demo', recordType: 'field_demo' },
          fields: [
            {
              editable: false,
              compact: false,
              label: 'ID',
              name: '_id',
              type: 'String',
            },
            {
              editable: false,
              compact: false,
              label: 'Created at',
              name: 'createdAt',
              timezone: 'Asia/Hong_Kong',
              type: 'DateTime',
            },
            {
              editable: false,
              compact: false,
              label: 'Updated at',
              name: 'updatedAt',
              timezone: 'Asia/Hong_Kong',
              type: 'DateTime',
            },
            {
              editable: true,
              compact: false,
              name: 'name',
              label: 'Name',
              type: 'String',
            },
            {
              editable: true,
              compact: false,
              name: 'textarea',
              label: 'Textarea',
              type: 'TextArea',
            },
            {
              editable: true,
              compact: false,
              name: 'dropdown',
              label: 'Dropdown',
              customOption: { enabled: true, label: 'Others' },
              defaultValue: 'A',
              nullOption: { enabled: false, label: 'Undefined' },
              options: [
                { label: 'Option A', value: 'A' },
                { label: 'Option B', value: 'B' },
                { label: 'Option S', value: 'S' },
              ],
              type: 'Dropdown',
            },
            {
              editable: true,
              compact: false,
              name: 'wysiwyg',
              label: 'Wysiwyg',
              type: 'WYSIWYG',
            },
            {
              editable: true,
              compact: false,
              name: 'datetime',
              label: 'Datetime',
              timezone: 'Asia/Hong_Kong',
              type: 'DateTime',
            },
            {
              editable: true,
              compact: false,
              name: 'boolean',
              label: 'Boolean',
              type: 'Boolean',
            },
            {
              editable: true,
              compact: false,
              name: 'integer',
              label: 'Integer',
              type: 'Integer',
            },
            {
              editable: true,
              compact: false,
              name: 'number',
              label: 'Number',
              type: 'Number',
            },
            {
              editable: true,
              compact: false,
              name: 'reference',
              label: 'Reference',
              displayFieldName: 'name',
              targetCmsRecord: { name: 'ref_demo', recordType: 'ref_demo' },
              type: 'Reference',
            },
            {
              editable: true,
              compact: false,
              name: 'back_refs',
              label: 'Back refs',
              sourceFieldName: 'reference',
              targetCmsRecord: {
                name: 'back_ref_demo',
                recordType: 'back_ref_demo',
              },
              displayFieldName: 'name',
              type: 'BackReference',
            },
            {
              editable: true,
              compact: false,
              name: 'back_refs_embedded',
              label: 'Back refs embedded',
              sourceFieldName: 'reference',
              targetCmsRecord: {
                name: 'back_ref_demo',
                recordType: 'back_ref_demo',
              },
              displayFields: [
                {
                  editable: false,
                  compact: false,
                  label: 'ID',
                  name: '_id',
                  type: 'String',
                },
                {
                  editable: true,
                  compact: false,
                  name: 'name',
                  label: 'Name',
                  type: 'String',
                },
              ],
              positionFieldName: 'field_demo_position',
              referenceDeleteAction: 'NullifyReference',
              references: [],
              reorderEnabled: false,
              sortOrder: 'Asc',
              type: 'EmbeddedBackReference',
            },
            {
              editable: true,
              compact: false,
              name: 'imageasset',
              label: 'Imageasset',
              nullable: true,
              type: 'ImageAsset',
            },
            {
              editable: true,
              compact: false,
              name: 'fileasset',
              label: 'Fileasset',
              accept: '',
              nullable: true,
              type: 'FileAsset',
            },
            {
              editable: true,
              compact: false,
              name: 'deleted',
              label: 'Deleted',
              defaultValue: false,
              type: 'Boolean',
            },
          ],
          label: 'Field demo',
          references: [
            {
              compact: false,
              name: 'reference',
              label: 'Reference',
              displayFieldName: 'name',
              targetCmsRecord: { name: 'ref_demo', recordType: 'ref_demo' },
              type: 'Reference',
            },
            {
              compact: false,
              name: 'back_refs',
              label: 'Back refs',
              sourceFieldName: 'reference',
              targetCmsRecord: {
                name: 'back_ref_demo',
                recordType: 'back_ref_demo',
              },
              displayFieldName: 'name',
              type: 'BackReference',
            },
            {
              compact: false,
              name: 'back_refs_embedded',
              label: 'Back refs embedded',
              sourceFieldName: 'reference',
              targetCmsRecord: {
                name: 'back_ref_demo',
                recordType: 'back_ref_demo',
              },
              displayFields: [
                {
                  compact: false,
                  editable: false,
                  label: 'ID',
                  name: '_id',
                  type: 'String',
                },
                { compact: false, name: 'name', label: 'Name', type: 'String' },
              ],
              positionFieldName: 'field_demo_position',
              referenceDeleteAction: 'NullifyReference',
              references: [],
              reorderEnabled: false,
              sortOrder: 'Asc',
              type: 'EmbeddedBackReference',
            },
          ],
        },
        list: {
          actions: [
            {
              href: '/records/{record_type}/new',
              label: 'Add',
              target: '',
              type: 'Link',
            },
            {
              label: 'Import records',
              name: 'import-field-demo',
              type: 'Import',
            },
            {
              label: 'Export records',
              name: 'export-field-demo',
              type: 'Export',
            },
          ],
          cmsRecord: { name: 'field_demo', recordType: 'field_demo' },
          defaultSort: { fieldName: 'name', order: 'descending' },
          fields: [
            {
              compact: true,
              editable: false,
              label: 'ID',
              name: '_id',
              type: 'String',
            },
            {
              compact: true,
              editable: false,
              label: 'Created at',
              name: 'createdAt',
              timezone: 'Asia/Hong_Kong',
              type: 'DateTime',
            },
            {
              compact: true,
              editable: false,
              label: 'Updated at',
              name: 'updatedAt',
              timezone: 'Asia/Hong_Kong',
              type: 'DateTime',
            },
            { compact: true, name: 'name', label: 'Name', type: 'String' },
            {
              compact: true,
              name: 'textarea',
              label: 'Textarea',
              type: 'TextArea',
            },
            {
              compact: true,
              name: 'dropdown',
              label: 'Dropdown',
              type: 'String',
            },
            {
              compact: true,
              name: 'wysiwyg',
              label: 'Wysiwyg',
              type: 'WYSIWYG',
            },
            {
              compact: true,
              name: 'datetime',
              label: 'Datetime',
              timezone: 'Asia/Hong_Kong',
              type: 'DateTime',
            },
            {
              compact: true,
              name: 'boolean',
              label: 'Boolean',
              type: 'Boolean',
            },
            {
              compact: true,
              name: 'integer',
              label: 'Integer',
              type: 'Integer',
            },
            { compact: true, name: 'number', label: 'Number', type: 'Number' },
            {
              compact: true,
              name: 'reference',
              label: 'Reference',
              displayFieldName: 'name',
              targetCmsRecord: { name: 'ref_demo', recordType: 'ref_demo' },
              type: 'Reference',
            },
            {
              compact: true,
              name: 'back_refs',
              label: 'Back refs',
              sourceFieldName: 'reference',
              targetCmsRecord: {
                name: 'back_ref_demo',
                recordType: 'back_ref_demo',
              },
              displayFieldName: 'name',
              type: 'BackReference',
            },
            {
              compact: true,
              name: 'imageasset',
              label: 'Imageasset',
              nullable: true,
              type: 'ImageAsset',
            },
            {
              compact: true,
              name: 'fileasset',
              label: 'Fileasset',
              accept: '',
              nullable: true,
              type: 'FileAsset',
            },
          ],
          filters: [
            { name: '_id', label: 'ID', nullable: false, type: 'String' },
            {
              name: '_created_at',
              label: 'CreatedAt',
              nullable: false,
              timezone: 'Asia/Hong_Kong',
              type: 'DateTime',
            },
            {
              name: '_updated_at',
              label: 'UpdatedAt',
              nullable: false,
              timezone: 'Asia/Hong_Kong',
              type: 'DateTime',
            },
            { name: 'name', label: 'Name', nullable: false, type: 'String' },
            {
              name: 'datetime',
              label: 'Datetime',
              nullable: false,
              timezone: 'Asia/Hong_Kong',
              type: 'DateTime',
            },
            {
              name: 'boolean',
              label: 'Boolean',
              nullable: false,
              type: 'Boolean',
            },
            {
              name: 'integer',
              label: 'Integer',
              nullable: false,
              type: 'Integer',
            },
            {
              name: 'reference',
              label: 'Reference',
              nullable: true,
              displayFieldName: 'name',
              targetCmsRecord: { name: 'ref_demo', recordType: 'ref_demo' },
              type: 'Reference',
            },
          ],
          itemActions: [
            {
              href: '/record/{record.id}',
              label: 'Show',
              target: '',
              type: 'Link',
            },
            {
              href: '/record/{record.id}/edit',
              label: 'Edit',
              target: '',
              type: 'Link',
            },
            {
              href: 'https://www.google.com/search?q={record.name}',
              label: 'Search',
              target: '_blank',
              type: 'Link',
            },
          ],
          label: 'Field demo',
          perPage: 25,
          predicates: [
            {
              name: 'deleted',
              type: 'NotEqualTo',
              value: true,
              valueType: 'JSONValue',
            },
          ],
          references: [
            {
              compact: true,
              name: 'reference',
              label: 'Reference',
              displayFieldName: 'name',
              targetCmsRecord: { name: 'ref_demo', recordType: 'ref_demo' },
              type: 'Reference',
            },
            {
              compact: true,
              name: 'back_refs',
              label: 'Back refs',
              sourceFieldName: 'reference',
              targetCmsRecord: {
                name: 'back_ref_demo',
                recordType: 'back_ref_demo',
              },
              displayFieldName: 'name',
              type: 'BackReference',
            },
          ],
        },
        new: {
          actions: [],
          cmsRecord: { name: 'field_demo', recordType: 'field_demo' },
          fields: [
            {
              editable: false,
              compact: false,
              label: 'ID',
              name: '_id',
              type: 'String',
            },
            {
              editable: false,
              compact: false,
              label: 'Created at',
              name: 'createdAt',
              timezone: 'Asia/Hong_Kong',
              type: 'DateTime',
            },
            {
              editable: false,
              compact: false,
              label: 'Updated at',
              name: 'updatedAt',
              timezone: 'Asia/Hong_Kong',
              type: 'DateTime',
            },
            {
              editable: true,
              compact: false,
              name: 'name',
              label: 'Name',
              type: 'String',
            },
            {
              editable: true,
              compact: false,
              name: 'textarea',
              label: 'Textarea',
              type: 'TextArea',
            },
            {
              editable: true,
              compact: false,
              name: 'dropdown',
              label: 'Dropdown',
              customOption: { enabled: true, label: 'Others' },
              defaultValue: 'A',
              nullOption: { enabled: false, label: 'Undefined' },
              options: [
                { label: 'Option A', value: 'A' },
                { label: 'Option B', value: 'B' },
                { label: 'Option S', value: 'S' },
              ],
              type: 'Dropdown',
            },
            {
              editable: true,
              compact: false,
              name: 'wysiwyg',
              label: 'Wysiwyg',
              type: 'WYSIWYG',
            },
            {
              editable: true,
              compact: false,
              name: 'datetime',
              label: 'Datetime',
              timezone: 'Asia/Hong_Kong',
              type: 'DateTime',
            },
            {
              editable: true,
              compact: false,
              name: 'boolean',
              label: 'Boolean',
              type: 'Boolean',
            },
            {
              editable: true,
              compact: false,
              name: 'integer',
              label: 'Integer',
              type: 'Integer',
            },
            {
              editable: true,
              compact: false,
              name: 'number',
              label: 'Number',
              type: 'Number',
            },
            {
              editable: true,
              compact: false,
              name: 'reference',
              label: 'Reference',
              displayFieldName: 'name',
              targetCmsRecord: { name: 'ref_demo', recordType: 'ref_demo' },
              type: 'Reference',
            },
            {
              editable: true,
              compact: false,
              name: 'back_refs',
              label: 'Back refs',
              sourceFieldName: 'reference',
              targetCmsRecord: {
                name: 'back_ref_demo',
                recordType: 'back_ref_demo',
              },
              displayFieldName: 'name',
              type: 'BackReference',
            },
            {
              editable: true,
              compact: false,
              name: 'back_refs_embedded',
              label: 'Back refs embedded',
              sourceFieldName: 'reference',
              targetCmsRecord: {
                name: 'back_ref_demo',
                recordType: 'back_ref_demo',
              },
              displayFields: [
                {
                  editable: false,
                  compact: false,
                  label: 'ID',
                  name: '_id',
                  type: 'String',
                },
                {
                  editable: true,
                  compact: false,
                  name: 'name',
                  label: 'Name',
                  type: 'String',
                },
              ],
              positionFieldName: 'field_demo_position',
              referenceDeleteAction: 'NullifyReference',
              references: [],
              reorderEnabled: false,
              sortOrder: 'Asc',
              type: 'EmbeddedBackReference',
            },
            {
              editable: true,
              compact: false,
              name: 'imageasset',
              label: 'Imageasset',
              nullable: true,
              type: 'ImageAsset',
            },
            {
              editable: true,
              compact: false,
              name: 'fileasset',
              label: 'Fileasset',
              accept: '',
              nullable: true,
              type: 'FileAsset',
            },
            {
              editable: true,
              compact: false,
              name: 'deleted',
              label: 'Deleted',
              defaultValue: false,
              type: 'Boolean',
            },
          ],
          label: 'Field demo',
          references: [
            {
              compact: false,
              name: 'reference',
              label: 'Reference',
              displayFieldName: 'name',
              targetCmsRecord: { name: 'ref_demo', recordType: 'ref_demo' },
              type: 'Reference',
            },
            {
              compact: false,
              name: 'back_refs',
              label: 'Back refs',
              sourceFieldName: 'reference',
              targetCmsRecord: {
                name: 'back_ref_demo',
                recordType: 'back_ref_demo',
              },
              displayFieldName: 'name',
              type: 'BackReference',
            },
            {
              compact: false,
              name: 'back_refs_embedded',
              label: 'Back refs embedded',
              sourceFieldName: 'reference',
              targetCmsRecord: {
                name: 'back_ref_demo',
                recordType: 'back_ref_demo',
              },
              displayFields: [
                {
                  compact: false,
                  editable: false,
                  label: 'ID',
                  name: '_id',
                  type: 'String',
                },
                { compact: false, name: 'name', label: 'Name', type: 'String' },
              ],
              positionFieldName: 'field_demo_position',
              referenceDeleteAction: 'NullifyReference',
              references: [],
              reorderEnabled: false,
              sortOrder: 'Asc',
              type: 'EmbeddedBackReference',
            },
          ],
        },
        show: {
          actions: [
            {
              href: '/record/{record.id}/edit',
              label: 'Edit',
              target: '',
              type: 'Link',
            },
          ],
          cmsRecord: { name: 'field_demo', recordType: 'field_demo' },
          fields: [
            {
              compact: false,
              editable: false,
              label: 'ID',
              name: '_id',
              type: 'String',
            },
            {
              compact: false,
              editable: false,
              label: 'Created at',
              name: 'createdAt',
              timezone: 'Asia/Hong_Kong',
              type: 'DateTime',
            },
            {
              compact: false,
              editable: false,
              label: 'Updated at',
              name: 'updatedAt',
              timezone: 'Asia/Hong_Kong',
              type: 'DateTime',
            },
            { compact: false, name: 'name', label: 'Name', type: 'String' },
            {
              compact: false,
              name: 'textarea',
              label: 'Textarea',
              type: 'TextArea',
            },
            {
              compact: false,
              name: 'dropdown',
              label: 'Dropdown',
              type: 'String',
            },
            {
              compact: false,
              name: 'wysiwyg',
              label: 'Wysiwyg',
              type: 'WYSIWYG',
            },
            {
              compact: false,
              name: 'datetime',
              label: 'Datetime',
              timezone: 'America/New_York',
              type: 'DateTime',
            },
            {
              compact: false,
              name: 'boolean',
              label: 'Boolean',
              type: 'Boolean',
            },
            {
              compact: false,
              name: 'integer',
              label: 'Integer',
              type: 'Integer',
            },
            { compact: false, name: 'number', label: 'Number', type: 'Number' },
            {
              compact: false,
              name: 'reference',
              label: 'Reference',
              displayFieldName: 'name',
              targetCmsRecord: { name: 'ref_demo', recordType: 'ref_demo' },
              type: 'Reference',
            },
            {
              compact: false,
              name: 'back_refs',
              label: 'Back refs',
              sourceFieldName: 'reference',
              targetCmsRecord: {
                name: 'back_ref_demo',
                recordType: 'back_ref_demo',
              },
              displayFieldName: 'name',
              type: 'BackReference',
            },
            {
              compact: false,
              name: 'asso_refs',
              label: 'Asso refs',
              associationRecordConfig: {
                cmsRecord: {
                  name: 'field_asso_ref',
                  recordType: 'field_asso_ref',
                },
                referenceConfigPair: [
                  {
                    compact: false,
                    name: 'field_demo',
                    label: 'Field demo',
                    displayFieldName: '_id',
                    targetCmsRecord: {
                      name: 'field_demo',
                      recordType: 'field_demo',
                    },
                    type: 'Reference',
                  },
                  {
                    compact: false,
                    name: 'asso_ref_demo',
                    label: 'Asso ref demo',
                    displayFieldName: '_id',
                    targetCmsRecord: {
                      name: 'asso_ref_demo',
                      recordType: 'asso_ref_demo',
                    },
                    type: 'Reference',
                  },
                ],
              },
              displayFieldName: 'name',
              sourceReference: {
                compact: false,
                name: 'field_demo',
                label: 'Field demo',
                displayFieldName: '_id',
                targetCmsRecord: {
                  name: 'field_demo',
                  recordType: 'field_demo',
                },
                type: 'Reference',
              },
              targetReference: {
                compact: false,
                name: 'asso_ref_demo',
                label: 'Asso ref demo',
                displayFieldName: '_id',
                targetCmsRecord: {
                  name: 'asso_ref_demo',
                  recordType: 'asso_ref_demo',
                },
                type: 'Reference',
              },
              type: 'AssociationReference',
            },
            {
              compact: false,
              name: 'back_refs_embedded',
              label: 'Back refs embedded',
              sourceFieldName: 'reference',
              targetCmsRecord: {
                name: 'back_ref_demo',
                recordType: 'back_ref_demo',
              },
              displayFields: [
                {
                  compact: false,
                  editable: false,
                  label: 'ID',
                  name: '_id',
                  type: 'String',
                },
                { compact: false, name: 'name', label: 'Name', type: 'String' },
              ],
              positionFieldName: 'field_demo_position',
              referenceDeleteAction: 'NullifyReference',
              references: [],
              reorderEnabled: false,
              sortOrder: 'Desc',
              type: 'EmbeddedBackReference',
            },
            {
              compact: false,
              name: 'imageasset',
              label: 'Imageasset',
              nullable: true,
              type: 'ImageAsset',
            },
            {
              compact: false,
              name: 'fileasset',
              label: 'Fileasset',
              accept: '',
              nullable: true,
              type: 'FileAsset',
            },
            {
              compact: false,
              name: 'deleted',
              label: 'Deleted',
              type: 'Boolean',
            },
          ],
          label: 'Field demo',
          references: [
            {
              compact: false,
              name: 'reference',
              label: 'Reference',
              displayFieldName: 'name',
              targetCmsRecord: { name: 'ref_demo', recordType: 'ref_demo' },
              type: 'Reference',
            },
            {
              compact: false,
              name: 'back_refs',
              label: 'Back refs',
              sourceFieldName: 'reference',
              targetCmsRecord: {
                name: 'back_ref_demo',
                recordType: 'back_ref_demo',
              },
              displayFieldName: 'name',
              type: 'BackReference',
            },
            {
              compact: false,
              name: 'asso_refs',
              label: 'Asso refs',
              associationRecordConfig: {
                cmsRecord: {
                  name: 'field_asso_ref',
                  recordType: 'field_asso_ref',
                },
                referenceConfigPair: [
                  {
                    compact: false,
                    name: 'field_demo',
                    label: 'Field demo',
                    displayFieldName: '_id',
                    targetCmsRecord: {
                      name: 'field_demo',
                      recordType: 'field_demo',
                    },
                    type: 'Reference',
                  },
                  {
                    compact: false,
                    name: 'asso_ref_demo',
                    label: 'Asso ref demo',
                    displayFieldName: '_id',
                    targetCmsRecord: {
                      name: 'asso_ref_demo',
                      recordType: 'asso_ref_demo',
                    },
                    type: 'Reference',
                  },
                ],
              },
              displayFieldName: 'name',
              sourceReference: {
                compact: false,
                name: 'field_demo',
                label: 'Field demo',
                displayFieldName: '_id',
                targetCmsRecord: {
                  name: 'field_demo',
                  recordType: 'field_demo',
                },
                type: 'Reference',
              },
              targetReference: {
                compact: false,
                name: 'asso_ref_demo',
                label: 'Asso ref demo',
                displayFieldName: '_id',
                targetCmsRecord: {
                  name: 'asso_ref_demo',
                  recordType: 'asso_ref_demo',
                },
                type: 'Reference',
              },
              type: 'AssociationReference',
            },
            {
              compact: false,
              name: 'back_refs_embedded',
              label: 'Back refs embedded',
              sourceFieldName: 'reference',
              targetCmsRecord: {
                name: 'back_ref_demo',
                recordType: 'back_ref_demo',
              },
              displayFields: [
                {
                  compact: false,
                  editable: false,
                  label: 'ID',
                  name: '_id',
                  type: 'String',
                },
                { compact: false, name: 'name', label: 'Name', type: 'String' },
              ],
              positionFieldName: 'field_demo_position',
              referenceDeleteAction: 'NullifyReference',
              references: [],
              reorderEnabled: false,
              sortOrder: 'Desc',
              type: 'EmbeddedBackReference',
            },
          ],
        },
      },
      field_demo_deleted: {
        cmsRecord: { name: 'field_demo_deleted', recordType: 'field_demo' },
        list: {
          actions: [
            {
              href: '/records/{record_type}/new',
              label: 'Add',
              target: '',
              type: 'Link',
            },
          ],
          cmsRecord: { name: 'field_demo_deleted', recordType: 'field_demo' },
          defaultSort: { order: 'undefined' },
          fields: [
            {
              compact: true,
              editable: false,
              label: 'ID',
              name: '_id',
              type: 'String',
            },
            {
              compact: true,
              editable: false,
              label: 'Created at',
              name: 'createdAt',
              timezone: 'Asia/Hong_Kong',
              type: 'DateTime',
            },
            {
              compact: true,
              editable: false,
              label: 'Updated at',
              name: 'updatedAt',
              timezone: 'Asia/Hong_Kong',
              type: 'DateTime',
            },
            { compact: true, name: 'name', label: 'Name', type: 'String' },
          ],
          itemActions: [
            {
              href: '/record/{record.id}',
              label: 'Show',
              target: '',
              type: 'Link',
            },
            {
              href: '/record/{record.id}/edit',
              label: 'Edit',
              target: '',
              type: 'Link',
            },
          ],
          label: 'Field demo deleted',
          perPage: 25,
          predicates: [
            {
              name: 'deleted',
              type: 'EqualTo',
              value: true,
              valueType: 'JSONValue',
            },
          ],
          references: [],
        },
      },
      ref_demo: {
        cmsRecord: { name: 'ref_demo', recordType: 'ref_demo' },
        edit: {
          actions: [],
          cmsRecord: { name: 'ref_demo', recordType: 'ref_demo' },
          fields: [
            {
              editable: false,
              compact: false,
              label: 'ID',
              name: '_id',
              type: 'String',
            },
            {
              editable: true,
              compact: false,
              name: 'name',
              label: 'Name',
              type: 'String',
            },
            {
              editable: true,
              compact: false,
              name: 'field_demos',
              label: 'Field demos',
              sourceFieldName: 'reference',
              targetCmsRecord: { name: 'field_demo', recordType: 'field_demo' },
              displayFieldName: 'name',
              type: 'BackReference',
            },
          ],
          label: 'Ref demo',
          references: [
            {
              compact: false,
              name: 'field_demos',
              label: 'Field demos',
              sourceFieldName: 'reference',
              targetCmsRecord: { name: 'field_demo', recordType: 'field_demo' },
              displayFieldName: 'name',
              type: 'BackReference',
            },
          ],
        },
        new: {
          actions: [],
          cmsRecord: { name: 'ref_demo', recordType: 'ref_demo' },
          fields: [
            {
              editable: false,
              compact: false,
              label: 'ID',
              name: '_id',
              type: 'String',
            },
            {
              editable: true,
              compact: false,
              name: 'name',
              label: 'Name',
              type: 'String',
            },
            {
              editable: true,
              compact: false,
              name: 'field_demos',
              label: 'Field demos',
              sourceFieldName: 'reference',
              targetCmsRecord: { name: 'field_demo', recordType: 'field_demo' },
              displayFieldName: 'name',
              type: 'BackReference',
            },
          ],
          label: 'Ref demo',
          references: [
            {
              compact: false,
              name: 'field_demos',
              label: 'Field demos',
              sourceFieldName: 'reference',
              targetCmsRecord: { name: 'field_demo', recordType: 'field_demo' },
              displayFieldName: 'name',
              type: 'BackReference',
            },
          ],
        },
        show: {
          actions: [
            {
              href: '/record/{record.id}/edit',
              label: 'Edit',
              target: '',
              type: 'Link',
            },
          ],
          cmsRecord: { name: 'ref_demo', recordType: 'ref_demo' },
          fields: [
            {
              compact: false,
              editable: false,
              label: 'ID',
              name: '_id',
              type: 'String',
            },
            { compact: false, name: 'name', label: 'Name', type: 'String' },
            {
              compact: false,
              name: 'field_references',
              label: 'Field references',
              sourceFieldName: 'reference',
              targetCmsRecord: { name: 'field_demo', recordType: 'field_demo' },
              displayFieldName: 'name',
              type: 'BackReference',
            },
          ],
          label: 'Ref demo',
          references: [
            {
              compact: false,
              name: 'field_references',
              label: 'Field references',
              sourceFieldName: 'reference',
              targetCmsRecord: { name: 'field_demo', recordType: 'field_demo' },
              displayFieldName: 'name',
              type: 'BackReference',
            },
          ],
        },
      },
      back_ref_demo: {
        cmsRecord: { name: 'back_ref_demo', recordType: 'back_ref_demo' },
        edit: {
          actions: [],
          cmsRecord: { name: 'back_ref_demo', recordType: 'back_ref_demo' },
          fields: [
            {
              editable: false,
              compact: false,
              label: 'ID',
              name: '_id',
              type: 'String',
            },
            {
              editable: true,
              compact: false,
              name: 'reference',
              label: 'Reference',
              displayFieldName: 'name',
              targetCmsRecord: { name: 'field_demo', recordType: 'field_demo' },
              type: 'Reference',
            },
            {
              editable: true,
              compact: false,
              name: 'name',
              label: 'Name',
              type: 'String',
            },
          ],
          label: 'Back ref demo',
          references: [
            {
              compact: false,
              name: 'reference',
              label: 'Reference',
              displayFieldName: 'name',
              targetCmsRecord: { name: 'field_demo', recordType: 'field_demo' },
              type: 'Reference',
            },
          ],
        },
        new: {
          actions: [],
          cmsRecord: { name: 'back_ref_demo', recordType: 'back_ref_demo' },
          fields: [
            {
              editable: false,
              compact: false,
              label: 'ID',
              name: '_id',
              type: 'String',
            },
            {
              editable: true,
              compact: false,
              name: 'reference',
              label: 'Reference',
              displayFieldName: 'name',
              targetCmsRecord: { name: 'field_demo', recordType: 'field_demo' },
              type: 'Reference',
            },
            {
              editable: true,
              compact: false,
              name: 'name',
              label: 'Name',
              type: 'String',
            },
          ],
          label: 'Back ref demo',
          references: [
            {
              compact: false,
              name: 'reference',
              label: 'Reference',
              displayFieldName: 'name',
              targetCmsRecord: { name: 'field_demo', recordType: 'field_demo' },
              type: 'Reference',
            },
          ],
        },
        show: {
          actions: [
            {
              href: '/record/{record.id}/edit',
              label: 'Edit',
              target: '',
              type: 'Link',
            },
          ],
          cmsRecord: { name: 'back_ref_demo', recordType: 'back_ref_demo' },
          fields: [
            {
              compact: false,
              editable: false,
              label: 'ID',
              name: '_id',
              type: 'String',
            },
            {
              compact: false,
              name: 'reference',
              label: 'Reference',
              displayFieldName: 'name',
              targetCmsRecord: { name: 'field_demo', recordType: 'field_demo' },
              type: 'Reference',
            },
            { compact: false, name: 'name', label: 'Name', type: 'String' },
          ],
          label: 'Back ref demo',
          references: [
            {
              compact: false,
              name: 'reference',
              label: 'Reference',
              displayFieldName: 'name',
              targetCmsRecord: { name: 'field_demo', recordType: 'field_demo' },
              type: 'Reference',
            },
          ],
        },
      },
      asso_ref_demo: {
        cmsRecord: { name: 'asso_ref_demo', recordType: 'asso_ref_demo' },
        show: {
          actions: [
            {
              href: '/record/{record.id}/edit',
              label: 'Edit',
              target: '',
              type: 'Link',
            },
          ],
          cmsRecord: { name: 'asso_ref_demo', recordType: 'asso_ref_demo' },
          fields: [
            {
              compact: false,
              editable: false,
              label: 'ID',
              name: '_id',
              type: 'String',
            },
            { compact: false, name: 'name', label: 'Name', type: 'String' },
          ],
          label: 'Asso ref demo',
          references: [],
        },
      },
    },
    site: [
      { type: 'UserManagement', label: 'USER' },
      { type: 'PushNotifications', label: 'PUSH' },
      { type: 'FileImport', label: 'FILE' },
      { type: 'Space', size: 'Medium' },
      { type: 'Record', name: 'field_demo', label: 'Field demo' },
      {
        type: 'Record',
        name: 'field_demo_deleted',
        label: 'Field demo deleted',
      },
      { type: 'Space', size: 'Large' },
    ],
    timezone: 'Asia/Hong_Kong',
    userManagement: { enabled: true },
  });
});
// tslint:enable:object-literal-sort-keys
