site:
  - type: Record
    name: topic
    label: Topic
  - type: Record
    name: poll
    label: All Polls
  - type: Record
    name: question
    label: Question
  - type: Record
    name: choice
    label: Choice
records:
  topic:
    list:
      fields:
        - name: name
          type: String
  poll:
    list:
      label: Polls
      perPage: 10
      fields:
        - name: name
          type: String
        - name: _created_at
          label: Created at
          type: DateTime
    show:
      label: View Poll
      fields:
        - name: name
          type: String
    edit:
      label: Edit Poll
      fields:
        - name: name
          type: String
  question:
    list:
      fields:
        - name: name
          type: String
  choice:
    list:
      fields:
        - name: name
          type: String
