site:
  - type: Record
    name: topic
    label: Topic
  - type: Record
    name: poll
    label: All Polls
  - type: Record
    name: question
    label: Question
  - type: Record
    name: choice
    label: Choice
records:
  topic:
    list:
      fields:
        - name: name
          type: String
  poll:
    list:
      label: Polls
      perPage: 10
      fields:
        - type: _id
        - name: name
          type: String
        # - name: user_id
        #   type: Reference
        - name: start_time
          type: DateTime
        - name: end_time
          type: DateTime
        # - name: image_id
        #   label: Image
        #   type: Image
        - name: is_active
          type: Boolean
        - name: is_live
          type: Boolean
        - name: likes
          type: Integer
        - name: answers
          type: Integer
        - name: views
          type: Integer
        # - name: country_id
        #   type: Reference
        - name: promoted
          type: Boolean
        - type: _created_at
        - type: _updated_at
    show:
      label: View Poll
      fields:
        - type: _id
        - name: name
          type: String
        - name: description
          type: String
        # - name: user_id
        #   type: Reference
        - name: start_time
          type: DateTime
        - name: end_time
          type: DateTime
        # - name: image_id
        #   label: Image
        #   type: Image
        - name: is_active
          type: Boolean
        - name: is_live
          type: Boolean
        - name: likes
          type: Integer
        - name: answers
          type: Integer
        - name: views
          type: Integer
        # - name: country_id
        #   type: Reference
        - name: promoted
          type: Boolean
        - type: _created_at
        - type: _updated_at
    edit:
      label: Edit Poll
      fields:
        - type: _id
        - name: name
          type: String
        - name: description
          type: String
        # - name: user_id
        #   type: Reference
        - name: start_time
          type: DateTime
        - name: end_time
          type: DateTime
        # - name: image_id
        #   label: Image
        #   type: Image
        - name: is_active
          type: Boolean
        - name: is_live
          type: Boolean
        - name: likes
          type: Integer
        - name: answers
          type: Integer
        - name: views
          type: Integer
        # - name: country_id
        #   type: Reference
        - name: promoted
          type: Boolean
        - type: _created_at
        - type: _updated_at
  question:
    list:
      fields:
        - name: title
          type: String
        - name: type
          type: String
        - name: poll_id
          type: Reference
          referencing: poll
          displayFieldName: name
        - name: ordering
          type: Integer
        - name: deleted
          type: Boolean
    show:
      fields:
        - name: title
          type: String
        - name: type
          type: String
        - name: poll_id
          type: Reference
          referencing: poll
          displayFieldName: name
        - name: ordering
          type: Integer
        - name: deleted
          type: Boolean
    edit:
      fields:
        - name: title
          type: String
        - name: type
          type: String
        - name: poll_id
          type: Reference
          referencing: poll
          displayFieldName: name
        - name: ordering
          type: Integer
        - name: deleted
          type: Boolean
  choice:
    list:
      fields:
        - name: name
          type: String
