site:
  - type: Record
    name: topic
    label: Topic
  - type: Record
    name: poll
    label: All Polls
  - type: Record
    name: question
    label: Question
  - type: Record
    name: choice
    label: Choice
records:
  topic:
    list:
      fields:
        - name: name
          type: String
  poll:
    list:
      label: Polls
      perPage: 10
      fields:
        - type: _id
        - name: name
          type: String
        - name: datetime
          label: Some Datetime
          type: DateTime
        - name: is_active
          type: Boolean
        - type: _created_at
        - type: _updated_at
    show:
      label: View Poll
      fields:
        - type: _id
        - name: name
          type: TextArea
        - name: datetime
          label: Some Datetime
          type: DateTime
        - name: is_active
          type: Boolean
        - type: _created_at
        - type: _updated_at
    edit:
      label: Edit Poll
      fields:
        - type: _id
        - name: name
          type: TextArea
        - name: datetime
          label: Some Datetime
          type: DateTime
        - name: is_active
          type: Boolean
        - type: _created_at
        - type: _updated_at
  question:
    list:
      fields:
        - name: name
          type: String
  choice:
    list:
      fields:
        - name: name
          type: String
