site:
  - type: Record
    name: topic
    label: Topic
  - type: Record
    name: poll
    label: All Polls
  - type: Record
    name: question
    label: Question
  - type: Record
    name: choice
    label: Choice
records:
  topic:
    list:
      fields:
        - type: _id
        - name: name
          type: String
        - name: image_id
          label: Image
          type: ImageAsset
        - type: _created_at
        - type: _updated_at
    show:
      fields:
        - type: _id
        - name: name
          type: String
        - name: image_id
          label: Image
          type: ImageAsset
        - type: _created_at
        - type: _updated_at
    edit:
      fields:
        - type: _id
        - name: name
          type: String
        - name: image_id
          label: Image
          type: ImageAsset
        - type: _created_at
        - type: _updated_at
    new:
      fields:
        - type: _id
        - name: name
          type: String
        - name: image_id
          label: Image
          type: ImageAsset
  poll:
    list:
      label: Polls
      perPage: 10
      fields:
        - type: _id
        - name: name
          type: String
        # - name: user_id
        #   type: Reference
        - name: topics
          type: Reference
          target: topic
          displayFieldName: name
          via_association_record: poll_topic
        - name: start_time
          type: DateTime
        - name: end_time
          type: DateTime
        - name: image_id
          label: Image
          type: ImageAsset
        - name: is_active
          type: Boolean
        - name: is_live
          type: Boolean
        - name: likes
          type: Integer
        - name: answers
          type: Integer
        - name: views
          type: Integer
        # - name: country_id
        #   type: Reference
        - name: promoted
          type: Boolean
        - type: _created_at
        - type: _updated_at
    show:
      label: View Poll
      fields:
        - type: _id
        - name: name
          type: String
        - name: description
          type: String
        # - name: user_id
        #   type: Reference
        - name: topics
          type: Reference
          target: topic
          displayFieldName: name
          via_association_record: poll_topic
        - name: start_time
          type: DateTime
        - name: end_time
          type: DateTime
        - name: image_id
          label: Image
          type: ImageAsset
        - name: is_active
          type: Boolean
        - name: is_live
          type: Boolean
        - name: likes
          type: Integer
        - name: answers
          type: Integer
        - name: views
          type: Integer
        # - name: country_id
        #   type: Reference
        - name: promoted
          type: Boolean
        - type: _created_at
        - type: _updated_at
    edit:
      label: Edit Poll
      fields:
        - type: _id
        - name: name
          type: String
        - name: description
          type: String
        # - name: user_id
        #   type: Reference
        - name: topics
          type: Reference
          target: topic
          displayFieldName: name
          via_association_record: poll_topic
        - name: start_time
          type: DateTime
        - name: end_time
          type: DateTime
        - name: image_id
          label: Image
          type: ImageAsset
        - name: is_active
          type: Boolean
        - name: is_live
          type: Boolean
        - name: likes
          type: Integer
        - name: answers
          type: Integer
        - name: views
          type: Integer
        # - name: country_id
        #   type: Reference
        - name: promoted
          type: Boolean
        - type: _created_at
        - type: _updated_at
    new:
      label: New Poll
      fields:
        - type: _id
        - name: name
          type: String
        - name: description
          type: String
        # - name: user_id
        #   type: Reference
        - name: topics
          type: Reference
          target: topic
          displayFieldName: name
          via_association_record: poll_topic
        - name: start_time
          type: DateTime
        - name: end_time
          type: DateTime
        - name: image_id
          label: Image
          type: ImageAsset
        - name: is_active
          type: Boolean
        - name: is_live
          type: Boolean
        - name: likes
          type: Integer
        - name: answers
          type: Integer
        - name: views
          type: Integer
        # - name: country_id
        #   type: Reference
        - name: promoted
          type: Boolean
  question:
    list:
      fields:
        - name: title
          type: String
        - name: type
          type: String
        - name: poll_id
          type: Reference
          target: poll
          displayFieldName: name
        - name: ordering
          type: Integer
        - name: deleted
          type: Boolean
    show:
      fields:
        - name: title
          type: String
        - name: type
          type: String
        - name: poll_id
          type: Reference
          target: poll
          displayFieldName: name
        - name: ordering
          type: Integer
        - name: deleted
          type: Boolean
    edit:
      fields:
        - name: title
          type: String
        - name: type
          type: String
        - name: poll_id
          type: Reference
          target: poll
          displayFieldName: name
        - name: ordering
          type: Integer
        - name: deleted
          type: Boolean
    new:
      fields:
        - type: _id
        - name: title
          type: String
        - name: type
          type: String
        - name: poll_id
          type: Reference
          target: poll
          displayFieldName: name
        - name: ordering
          type: Integer
        - name: deleted
          type: Boolean
  choice:
    list:
      fields:
        - name: name
          type: String
association_records:
  poll_topic:
    fields:
      - name: poll_id
        type: Reference
        target: poll
      - name: topic_id
        type: Reference
        target: topic
